dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    #define a yaml reference to the common packages, and use this in the matrix below. The matrix overwrites the local "addons" so this is nessesary
    packages: &trusty_packages
      - cmake
      - make
      - libfftw3-dev
      - libboost-all-dev
#      - ruby-rdiscount
#      - ruby-hpricot
#      - ruby-mustache
#      - ruby-ronn
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - *trusty_packages
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - *trusty_packages
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - *trusty_packages
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - *trusty_packages
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - *trusty_packages
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

language: cpp
compiler:
  - gcc
install:
#  # the ubuntu ruby packages appear to be too old, so install via gem
  - gem install rdiscount hpricot mustache:0.99.6 ronn
before_script:
  - mkdir build && cd build
  - cmake  -DBoost_NO_BOOST_CMAKE=ON ..
script:
  - make package
  - cpack -G DEB
after_success:
  - sudo dpkg -i scape-xcorrsound*deb
  - ls -l scape-xcorrsound*deb
  - overlap-analysis -h
  - sound-match -h
  - waveform-compare -h
